import React, { Component } from 'react';
import { Link } from 'react-router-dom';


export default class Blog9 extends Component {

    render(){
        return(
            <section className='Blog-Text'>
                <section>
                   <h1>The Digital Fragility of The Starry Night</h1>
                   <section>
                       <article>
                       This paper is divided into three sections, with each section answering the questions set by the exam brief. The first question, we will define the term “Digital Fragility” using the required reading as a reference alongside some external sources. The second question, we will discuss migration, a method used to account for digital fragility in artworks, and other digital medium content. Finally, we will look at the Vincent van Gogh’s The Starry Night 3D model with reference to the required reading.
                      </article>
                      <h2>
                      What is Digital Fragility?
                      </h2>
                      <article>
                      In my recent research into intermedial studies, Bruhn and Schirrmacher, describe 4 modalities of media, two of them being; material modality and spatiotemporal modality (Bruhn & Schirrmacher, Intermedial Studies, 2022). Material modality refers to what gives the medium form, the interface of communication. While spatiotemporal modality refers to how the artefact is perceived in space and time. In our case I would like us to think of the material modalities as the hardware and software we use to experience digital art, while the spatiotemporal modality is the digital art itself and the world it created within it. 
In their paper, Rubio and Wharton, refer to this spatiotemporal space as a “dis-embedded view”, a “virtual space not bounded by terrestrial laws” (Rubio & Wharton, 2022). This does not mean that digital art can be created without limitations, its limits lie within its material modalities. Which is why they also refer to the material modalities as the “Short comings” of the digital (Rubio & Wharton, 2022). Material modes all have a lifespan, which is also very unpredictable. Hardware can be physically damaged, become incompatible with other hardware and many other reasons, while digital data itself decays over time through the various processes it goes through like transmissions. This I what leads to Technology obsolescence. Technology is constantly advancing, and the technology that was, becomes obsolete, and ultimately replaced by new technology. This leaves the media products created in or with those technologies non-functional. 
On 31 December 2020, the world of internet art changed when Adobe flash made the decision to discontinue the Flash plug-in (Mladentseva, 2022). This was ultimately due to a newer technology, HTML5, that could perform the functionalities of Flash without the unnecessary plug-ins which raised many concerns especially in terms of security. But what happened to the digital art created using Flash? Well, they were all simply gone with a flash. I experienced the effects as well, while trying to research net art, I constantly stumbled upon non-functional artefacts that were created using Flash, and this made my research even more difficult. But this is what “Digital Fragility” is, the unstable and unpredictable behaviour of the digital world. 
As a digital artist there are two things that concern me with regards to digital fragility. The loss of my work personally does not and should not affect me if I can retrieve it again, which is why I always try to keep backups, and making use of source control software like GitHub. It has come to the point where I don’t only upload my game projects, but any files or papers I have written are also uploaded. But absent worry of lose seems to only be transferred to what also leads to the first concern I have, which is the possibility of the loss of functionality of my work. Looking at the case of Flash, many artefacts, including animations and games were lost through the dis-continuing of the plug-in. what will happen to my work if GitHub is no longer there? The second being the fragility that seeps into the market, causing what I would like to call market fragility. What happens when there is a technology that exceeds my skills as a developer? Look at the case of web development, why should companies hire someone when the current technology allows them to make their own basic sites? what happens when this technology advanced further? We, ourselves will ultimately be rendered obsolete.

                      </article>
                      <h2>Migrating to Migration  </h2>
                      <article>
                      With the threat of the ever-so unpredictable fragility of the digital as defined above, migration serves as a what I see as a temporary solution to prolonging the life of a digital artefact. So, what is migration? We have already seen why it is necessary because of digital fragility, both art and form are fragile and impermanent. As Rubio and Wharton have pointed out, digital art does not respect the time they were made, and to survive they must continuously be updated (Rubio & Wharton, 2022). This update takes place through the processes of migration. Migration in simple terms is transferring of the media-based contents, the spatiotemporal world created by the art, from older technologies to newer ones. An example given in the text is the transfer from laser disc, a now obsolete technological medium, to Blu-ray disc. 
Diving further into the text, they look the Museum of Modern Art (MOMA) and how they deal with conserving artworks through migration. The text also points out that this method of conservation is method that has been used throughout history and not just used on digital products. 
“Raphael’s Madonna di Foligno (1511), now in the Vatican museum, was transferred from wood to canvas in 1801.” (Rubio & Wharton, 2022).
But due to the fragile nature of digital art even this process of trying to prevent the effects of fragility renders the artwork vulnerable and could potentially damages the artefact through the process. Similar to how when one transferers a file, but it becomes corrupted when its only done so in parts and not in full. Rubio and Wharton acknowledge this and identify digital content and “inherently relational” (Rubio & Wharton, 2022). Which is seen as one of the challenges of migration. Digital artefacts, exist within a medium consisting of various material modalities, various elements that allows it to exist. If one of these elements are missing it will render the artefact useless. In the media workstation, at MOMA, this process of migration is achieved through not only moving the digital media content, but also by sustaining the medium which allows the artefact to exist and remain functional (Rubio & Wharton, 2022).
We have stated before that digital artefacts do not respect the construct of time, and therefore due to the process of migration they refer to the object as a circulating object not bound by a single moment in time but rather defined by its existence across multiple times (Rubio & Wharton, 2022).
Why is this migration necessary? Digital artefacts need to become circulating objects. Without this necessary circulation process or if it should come to a halt, this will render the artefact stable within time, anchoring it on moment in history, but it will also render the artefact along with the medium that anchors it obsolete. So, the question is whether the artefact should die with its medium or live on through another despite the difficult process. 
Which begs the question: what is the mission of the conservator? In a paper, The acceptance of ephemerality and the idea of deterioration, written by Ruth del Fresno Guillem, they explore the idea of impermanence and what is the mission of the conservator. While referencing the work of Wharton, they state the following: 
“conservators’ mission is to conserve the cultural significance of an object or artwork, and this most typically resides in the conceptual intention of the artist.” - (Guillem, 2022)
This looks at the contradictions faced by the conservator, when deciding to preserve an artwork through migration of any other means. Migration and the purpose of safe keeping in museums is essentially results in the use of copying original digital artefacts. Which brings up another question of originality. And due to the process of migration this process is continuously circulating, which means that the process of making copies never ceases. While Rubio and Wharton see this process as something that can not be stop, Guillem questions this as to why should an artwork not be allowed to die. He sees preservation of an artefact as the preservation of the artists intent. (Guillem, 2022)
But what happens when this intent is for the artwork to become a time-based medium, which is doomed to die. This produces an ethical paradox within in conservation. Guillem looks at the case of Dolores Invisibles created by SinQuenza in 2014 (Guillem, 2022). The artefact was created using technology that was rendered obsolete due to the simple fact that it was meant to die. In a second case study, Guillem looks at the work of Sergio Porlán, and their artwork Corpe.  Porlán also stated that his work is not meant to last, and after the artefact reaches its death, he will no longer acknowledge it as his own work. Guillem then conclude with the statement: 
“The authenticity of the artwork is not in the constituent materials but the idea and the artist's will.”- (Guillem, 2022)
Which brought to my attention, and perhaps has also influenced my views on authenticity, that authenticity is matter defined by the artist themselves and no one else. The choice of migration is only rendered necessary if the artists deem so. Should they agree, they still become part of the process, and I see this as the artwork’s authenticity remaining intact due to the creator being a part of the process. This does however lead to the question:
Is a piece of digital art as a circulating object of migration ever truly completed?

                      </article>
                      <h2>Into The Starry Night </h2>
                      <article>
                      This section we will analyse The Starry Night by Vincent van Gogh as a stable object turned fragile. While I do believe that the results of this, being the 3D model, has some relations of being a distributed artefact with multiple creators forming its creation, we will focus on digital fragility and authenticity. While doing this analysis I will be using the text of Rubio and Wharton as a guideline as they address digital artifacts as circulating object to object that raise concerns with regards to their authenticity.
The original painting of Vincent van Gogh’s The Starry Night is located at MOMA, but it also shares this location with its 3d model digital reproduction. The Image & Virtual Resources (IVR) team at MOMA wanted an ideal way to capture the painting as an image. The role of a museum is to makes the cultures and heritages that it holds to become a part of our lives, with the focus being on the experiences of its visitors (Li, Liew, & SU, 2022). This mission raises two points that museums must confront, the use of technology and the enhancement of the visitor’s experience, while also considering the effects of the recent pandemic. 
The users experience as we have seen through the art of games is especially essential to how one engages with an artefact.  In this case the museum must aim to extend the amount of time a visitor spends on an artwork so that they may not only appreciate it more but also increase their knowledge of the subject. 
This was the intention of the team at MOMA, when they decided to recreate The Starry night as a 3D virtual Model. They made use of the recent technological material modalities at hand in order to reproduce the painting, making it more immersive than what a simple 2D picture would have been. According to MOMA’s site and also the site where this 3d virtual model can be found and experienced, they had 2 main goals that aligned with this (MOMA, 2022);
•	Produce a high-resolution, extremely colour accurate image with ideal lighting
•	Create something more than just a still 2D Image. 
They achieved this through a 3D modelling technique called Photogrammetry. This is a process of extracting 3D information from photographs, which then involves overlapping these photographs and converting them into a 3D model. This allowed the IVR team to create The Starry night model, but already we encounter the use of mechanical reproduction of the painting. 

                      </article>
                      <h2>The Starry Night is Circulating</h2>
                      <article>
                      With the introduction of mechanical reproduction to the paper, we must look at the works of Benjamin Walter and anything related to the topic. We have already seen just how migration is used, and through an example from the Rubio and Wharton, we have seen that migration even occurred by removing a mural from wood and transferring it to a canvas. The photogrammetry technique already raises question of authenticity, which we will get to. What happens after the process of photogrammetry is also important to the case of Benjamin’s work, which is the was transferring this captured information into data, using a piece of computational technology to compute the information, and ultimately rendering the virtual space allowing us as uses to perceive the artwork. This process of creation placed the effects of digital fragility on the essence of The Starry Night’s existence (this does not mean that the physical painting can be lost due to digital fragility). The artefact has been reproduced twice, and each time they used two different methods, the first being mechanical reproduction and the second being digital reproduction. The example given before showed migration from on physical medium to another, but after the second reproduction we see migration completely changing the medium in which The Starry Night exists. This is what led to digital fragility, the process of migration that was meant to grant a sense of immortality on digital artifacts was used to create a digital artefact from an analogue artefact. 
                      </article>
                      <h2>The Multiple Stars in The Starry Night.  </h2>
                      <article>
                      This process of creation not only brought upon the digital fragility but also the issues of originality.  While it remains clear now that the original artwork is the painting. While there are methods in place to distinguish between original and copy within a analogue medium, Rubio and Wharton look to the issues that revolve around the distinctions between original and copy within a digital space. On of those issues being the fact that some copies have been reduced and potentially  result in a loss of information regarding the digital artefact.  In terms of The Starry Night already the movement from analogue to a digital medium, resulted in a reduction in the artwork itself. On the site they even state that in order to make this virtual experience accessible as it was intended to be, they had to ultimately reduce the detail of the model. Already some of the essence of the original is lost. 
This multiplication of the original does not stop there, because The Starry night was brought into a digital space, we have already seen that it needs to rely on migration and other conservation techniques to survive.  These methods however result in a system that we will refer to as a copy of copies. Due to digital fragility, multiple copies are made to keep an artefact alive, this is done for the sake of safe keeping, with each iteration of migration resulting in more and more copies (Rubio & Wharton, 2022). This leads Rubio and Wharton to a specific question.
How do museums enforce the distinction between original and copy, and how they prevent the loss of control over these objects? 
Which leads us to the next section of the paper and also the next section of Rubio and Wharton’s reading. The effect that migration and conservation as whole has over the authenticity of an artefact. 

                      </article>
                      <h2>Who Are the Real Stars in The Night? </h2>
                      <article>
                      If artworks could maintain a stable identity, they would not be required to move from one medium to another, they would not have to considered circulating objects. If this was the case authentication would not be an issue, rather keeping the artwork alive would be the only concern (Rubio & Wharton, 2022). But this is not the case, digital fragility results in migration which further raises the concerns of authenticity. 
The work of Walter Benjamin looks at the concept of aura, a phenomenon that surrounds artworks and their uniqueness (Benjamin, 2022). With increase advancement of technology this aura was then questioned and thought to be destroyed once an artwork is reproduced, rendering it no longer unique. 
Migration changes the inner structure of an artefact as well as its material modalities (Rubio & Wharton, 2022). When we migrate an artefact, we are not moving the same object, rather we are regenerating a new artefact within a different medium, Rubio and Wharton refer to a circulating object as multiple objects across multiple platforms (Rubio & Wharton, 2022).  And this is exactly where the debate of authenticity comes from. The original The Starry Night as a painting is not same artefact as the 3D model we see on the website of MOMA. Each of them having different material modalities, spatiotemporal modalities (although the content is the same) as well as sensorial modalities (Bruhn & Schirrmacher, 2022). But if each is considered to be a different object, how would one determine what came first. 
This pushes to look at aura within the digital. The Aura of Information is the separation of the meaning present in a work from the physical form of that work (Betancourt, 2022). In our case this separation occurs from the analogue medium of The Starry Night painting and its information into the form of ones and zeros. Betancourt argues that Benjamin’s proposal regarding the aura of artwork is not destroyed, rather its reproduction extends the aura of an artwork. He does by referring to the work of Hans Abbing, who suggest that authenticity only becomes valuable once it has been reproduced (Betancourt, 2022). This ultimately leads us to think of aura as a function of reproduction rather than something that destroyed through reproduction, creating a dualism nature surrounding The Starry Night.  The aura that was originally present in the painting is still there but now the aura also refers to the unique relation between the “multiple objects across multiple mediums”.
Betancourt then looks at authenticity of one of these multiple objects, in our case the 3d virtual model, and claims that its authenticity lies within its ability to remain independent if the effects of time, whereas the painting cannot. The effects of time in this case should not be confused with digital fragility, which is what I believe truly defines the authenticity of digital artefact. If what Betancourt says is taken into account, I see the process of reproduction as something that ultimately gives rise to a new sense of aura and authenticity that surround the now 3D model of The Starry Night. This renders the digital artefact authentic in its own sense. 


                      </article>
                   </section>
                   
               </section>
               
                <section>
                <section>
                <article>
               <button className='btn'><Link  to="/blogs">Back</Link></button>
               
               </article>
                </section>
                     <h5>References</h5>
                     <ul>
                         <li>Benjamin, W. (2022). The Work of Art in the Age of Mechanical Reproduction .</li>
                         <li>Betancourt, M. (2022). The Aura of the Digital. In M. Betancourt, The Critique of Digital Capitalism. Punctum Books.</li>
                         <li> Bruhn, J., & Schirrmacher, B. (2022). Intermedial Studies. Routledge.</li>
                         <li> Guillem, R. d. (2022). The Acceptance of Ephemerality and the idea of Deterioration.</li>
                         <li>Li, Y.-C., Liew, A.-C., & SU, W.-P. (2022). THE DIGITAL MUSEUM: CHALLENGES AND SOLUTION. </li>
                         <li>Mladentseva, A. (2022). Responding to obsolescence in Flash-based netart: a case study on migrating Sinae Kim’s Genesis. </li>
                         <li> MOMA. (2022). Retrieved from MOMA Magazine: https://www.moma.org/magazine/articles/462</li>
                         <li>Rubio, F. D., & Wharton, G. (2022). The Work of Art in the Age . </li>
                     </ul>
                </section>
            </section>
        )
    }
}